name: BoxServerPlugin
version: '0.1-Beta'
main: me.treacpe.boxServerPlugin.BoxServerPlugin
api-version: '1.21'
author: Treacpe
commands:
  boxmenu:
    description: Opens the Box Menu GUI
    usage: /bm , /boxm , /boxmenu
    permission: boxserver.menu